apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base/
patchesStrategicMerge:
- |- 
    apiVersion: operator.tigera.io/v1
    kind: Installation
    metadata:
      name: default
    annotations:
      "helm.sh/hook": post-install
    spec:
    # Configures Calico policy configured to work with AmazonVPC CNI networking.
    cni:
      type: AmazonVPC
